version: '3.9'
services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db 

  migrate:
    image: golang:1.22-alpine
    container_name: goose_migrate
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      go_db:
        condition: service_healthy
    entrypoint: >
      sh -c "
        go install github.com/pressly/goose/v3/cmd/goose@latest &&
        goose -dir ./db/migrations postgres postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable up
      "
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: